name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@v0.2.0
        with:
          root_file: readout-board-docs.tex
          args: "-f -pdf -latexoption=-shell-escape -latexoption=-file-line-error -latexoption=-interaction=nonstopmode"
      - name: Attach artifact
        uses: actions/upload-artifact@v2
        with:
          name: readout-board-docs.pdf
          path: readout-board-docs.pdf
